name: Deploy to EC2
 
on:
  push:
    branches:
      - main  # or your deployment branch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
 
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_APP_DIR }}
          git pull origin main
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
        EOF
